;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-delete-forward
        c-indent-line-or-region
        electric-newline-and-maybe-indent
        helm-show-kill-ring
        ignore
        indent-for-tab-command
        kill-region
        markdown-exdent-or-delete
        org-beginning-of-line
        org-delete-char
        org-kill-line
        org-self-insert-command
        org-yank
        sgml-slash
        sh-assignment
        ))

(setq mc/cmds-to-run-once
      '(
        next-buffer
        org-cycle
        python-indent-electric-colon
        yaml-electric-backspace
        ))
