;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-newline-and-maybe-indent
        helm-show-kill-ring
        ignore
        kill-region
        markdown-exdent-or-delete
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-self-insert-command
        org-yank
        toggle-input-method
        ))

(setq mc/cmds-to-run-once
      '(
        next-buffer
        org-cycle
        ))
